# Convirtiendo lista de python a array numpy

Al ejecutar el codigo nos arrojara un objeto de tipo array de numpy

In [10]:
import numpy as np

list_numbers = [1,2,3,4,5]
arr = np.array(list_numbers)
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

# Creacion de matrices, listas de multiples dimensiones

- Crearemos una lista de listas en python.

In [11]:
matriz_list = [[1,2,3], [4,5,6], [7,8,9]]

- Al convertirla en un array de numpy, obtenemos una matriz de dos dimensiones.

In [14]:
matriz = np.array(matriz_list)
print(matriz)
type(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

# Creando un indexado
Para poder acceder a los valores de una lista en python simplemente escribimos el nombre con el que se identifica esta lista seguido de la notacion de corchetes y dentro la posisicion del valor que necesitamos y de esta forma podemos realizar multiples operaciones con los datos.

In [18]:
print(arr[0])
print(arr[1])

print(arr[1] + arr[3])

1
2
6


## Accediendo a las posiciones en las matrices

In [19]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Al observar la estrructura de la matriz podemos imaginarnos una tabla de filas y columnas. 

Podemos acceder a la primera fila con la notacion de corchetes seguido de la posicion de esta, en este caso es la posicion 0

La segunda fila corresponde a la posicion1, y la ultima a la posicion 2.

In [20]:
print(matriz[0])
print(matriz[1])
print(matriz[2])

[1 2 3]
[4 5 6]
[7 8 9]


Para poder acceder a los valores de la matriz individualmente, indicaremos por medio de corchetes dos valores.
- El primero correposndera a la fila en donde se ubica el valor que necesitemos
- El segundo inbdicara la columna en la que se encuentra el valor.
En este caso la matriz esta conformada de 3 filas y 3 columnas.

Ejemplo:
Necesitamos guardar en una variable el valor 3 y 5 de la matriz antes hecha.

In [21]:
first_num = matriz[0,2]
second_num = matriz[1,1]

print(first_num, second_num)

3 5


Asi de sencillo es llegar a indices a nivel de objetos de numpy como el array.

## Accediendo a multiples indices a traves de slice


- Sintaxis
    ~~~
    lista[posicion_inicial:posicion_final]
    ~~~

Por medio del slicing podemos almacenar en una variable una lista de elementos a partir del index en el que se encuentran.

En neste ejemplo obtendremos los valores del indice 0 al 2, indicaremos en el slice que el limite sera el indice 3, y este ultimo no sera tomado en cuenta.


In [22]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr[0:3]

array([1, 2, 3])

Esto es muy valioso en ciencia de datos ya que no queremos todo el array si no una posicion en concreto.

Existe otro parametro mas dentro del slicing, y este es el paso. Es decir, mandamos a llamar las posiciones de inicio y fin pero podemos llamarlos de dos en dos o de tres en tre etc. segun sea el caso.

- Primero mandaremos a llamar todo.

In [27]:
arr[:]

array([1, 2, 3, 4, 5])

- Mandaremos a llamar a partir del indice 2 y no indicaremos la posicion final. Esto nos traera todo el arraya a partir del indica dado.

In [28]:
arr[:3]

array([1, 2, 3])

- Ahora mandaremos a llamar toda la lista o array e indicaremos que sera de dos en dos.

In [29]:
arr[::2]

array([1, 3, 5])

Esto corresponde a las posiciones 0, 2, 4.
De esta forma definimos los pasos en los que necesitamos el array.
### Ejecutando slice hacia atras.
Si necesitamos el ultimo valor, podemos mandar a llamarlo por medio del -1, es decir del indice 0 uno atras, y nos devolvera su valor.
Esto es util cuando necesitamos el ultimo valor de alguna coleccion de datos y no sabemos conseguridad cual es, ni el tamano de la lista.

In [30]:
arr[-1]

5

## Ejcutando slicing en matrices

In [31]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El primer valor que mandamos correspondera a las filas.


In [37]:
matriz[1:,]

array([[4, 5, 6],
       [7, 8, 9]])

En el segundo valor del slice indicamos que nos devuelva las posiciones de la 0 a la dos de cada fila.


In [42]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])