In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

# Tipos de datos en numpy

Numpy ofrece una amplia gama de tipos de datos, siendo el tipo flotante el más comúnmente utilizado. Esto se debe a que resulta especialmente conveniente para integrarse con bibliotecas como TensorFlow o PyTorch, que son populares en el ámbito de las redes neuronales y el aprendizaje automático.

Para esto definiremos el mismo array de arriba pero indicando que es flotante.

In [2]:
arr = np.array([1,2,3,4,5], dtype='float64')
arr.dtype

dtype('float64')

## Convirtiendo un array de tipo entero a flotante

Habrá ocasiones en las que recibiremos datos en formato entero y será necesario convertirlos a formato de punto flotante. Para lograrlo, utilizaremos el método astype, especificando el tipo de dato al que queremos convertirlos.

Definiremos otro arreglo y realizaremos las operaciones sobre él.

In [7]:
new_arr = np.array([1,2,3,4,5])
new_arr

array([1, 2, 3, 4, 5])

In [9]:
new_arr = new_arr.astype(np.float64)
new_arr

array([1., 2., 3., 4., 5.])

## Convirtiendo de entero a booleano

Vamos a modificar uno de nuestros arrays agregando un cero.

En lógica booleana, el valor 0 siempre se considera falso, mientras que cualquier número igual o mayor a 1 se considera verdadero.

In [10]:
new_arr = np.array([0,1,2,3,4,5,0])

int_to_bool = new_arr.astype(np.bool_)
int_to_bool

array([False,  True,  True,  True,  True,  True, False])

## Convirtiendo de entero a string y viceversa

In [12]:
int_to_str = new_arr.astype(np.string_)
int_to_str

array([b'0', b'1', b'2', b'3', b'4', b'5', b'0'], dtype='|S21')

Al ejecutar el codigo nos devuelve una lista y nos indica el tipo de dato.

Ahora realizaremos la operacion a la inversa, crearemos un array de strings y los convertiremos a enteros.

In [13]:
arr_str = np.array(['1','2','3'])
arr_str

array(['1', '2', '3'], dtype='<U1')

In [14]:
arr_str_to_int = arr_str.astype(np.int8)
arr_str_to_int

array([1, 2, 3], dtype=int8)

**El array de numpy solo puede tener un unico tipo de dato con el que va a trabar, no podemos tener la mitad del array en int y la otra mitad en float o bool, esto haria que pierda toda la optimizacion de numpy al momento de almacenar en memoria y trabajar con los distintos tipos de datos.**