# Dimensiones

Dentro del mundo de la ciencia de datos podemos tener multiples dimensiones y es importante detectarlas y saber como trabajar con ellas.

## Tipos de dimensiones

- Scalar: Es un término que se refiere a un valor único, es decir, un valor que no tiene dimensiones ni forma.
- Vector: Es un tipo de dato en form de lista que puede llegar a alamacenar distintos valores. Al ser una lista de python consta de una unica dimension. En terminos mas simples un vector es una matriz unidimensional.
- Matrix, Matriz: Es una estructura de datos formada por dos dimensiones, contiene datos y valores organizados en filas y columnas. Cada elemento contienen dos indices uno, que hace referencia a su fila y otro a su columna. Si lo pensamos en listas de python, seria similar a una lista de listas.
- Tensor: Es un arreglo multidimensional con cualquier numero de dimensiones. 
    - Un tensor tridimensional podría representar un volumen de datos, como una pila de imágenes en 3D.
    - Un tensor cuatridimensional podría representar una secuencia de volúmenes en 3D, como una secuencia de video.
    > Lista de listas con listas en su interior [lista[de listas[con listas] ] ] 


<div>
<p style = 'text-align:center;'>
<img src="./img/dimensionesDatos.png" alt="Dimensiones" width="500px">
</p>
</div>



Crearemos unos ejemplos en diferentes dimensiones y por medio de la propiedad <code>.ndim</code> obtendremos el numero de dimensiones.

In [3]:
import numpy as np

scalar = np.array(21)
scalar.ndim

0

In [4]:
scalar = np.array([1,2,3,4])
scalar.ndim

1

In [6]:
matriz = np.array([[1,2,3],[4,5,6],[2,3,4],[5,6,7],[19,24,34]])
print(matriz)
matriz.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 2  3  4]
 [ 5  6  7]
 [19 24 34]]


2

In [10]:
tensor = np.array([[[1,2,3],[4,5,6],[2,3,4],[5,6,7],[19,24,34]],[[1,2,3],[4,5,6],[2,3,4],[5,6,7],[19,24,34]]])
print(tensor)
tensor.ndim

[[[ 1  2  3]
  [ 4  5  6]
  [ 2  3  4]
  [ 5  6  7]
  [19 24 34]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 2  3  4]
  [ 5  6  7]
  [19 24 34]]]


3

## Agregar o eliminar dimensiones

### Agregar

- Definiremos un vector sencillo al que le agregaremos la propiedad  ``ndmin`` que nos indica la cantidad minima de dimensiones.
Al imprimirlo y al aplicarele el metodo ``ndim`` observaremos que a pesar de tratarse de un vector de una sola dimension, realmente numpy ya lo esta tratando como un arreglo multidimencional, limitando su tamano al numero que pasamos como parametro.

In [11]:
new_array = np.array([1,2,3], ndmin=10)
print(new_array)
new_array.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

- Agregaremos dimensiones a un vector previamente definido de una sola dimension.
    - Utilizaremos un metodo de numpy llamado ``.expand_dims``, literalmente expandira sus dimensiones al array que se le aplique.
    - Recibe como primer parametro el array a expandir.
    - Como segundo parametro indicamos el axis a expandir. En numpy y en python el  ***axis 0 hace referencia a las filas***, mientras que el ***axis 1 a las columnas*** 

In [12]:
array_uni = np.array([1,2,3])
print(array_uni)
array_uni.ndim

[1 2 3]


1

Este metodo se puede aplicar a cualquier array tanto en el 0 como en el eje 1

In [13]:
expand_vec = np.expand_dims(array_uni, axis=0)
print(expand_vec)
expand_vec.ndim

[[1 2 3]]


2

### Eliminar

- squeeze: Este metodo comprime el numero de dimensiones de un vector al numero correcto que se esta utilizando.
    - Recibe como primer parametro el array a reducir
    - Como segundo parametro ``axis`` (opcional): Especifica los ejes a los cuales aplicar el squeeze. Si se proporciona, solo se eliminarán las dimensiones de tamaño 1 en los ejes especificados. Si no se proporciona, se eliminarán todas las dimensiones de tamaño 1.

    En este ejemplo definimos nuestro vector con 10 dimensiones pero solo se esta utilizando una dimension, por tanto sera reducido a las dimensiones que se utilizan.

In [14]:
print(new_array)
new_vector = np.squeeze(new_array)
print(new_vector)
new_vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]
[1 2 3]


1