In [1]:
import numpy as np

numbers_list = np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- `np.arange`: Devuelve una lista de numeros segun el rango que definamos.
    - Como primer parametro recibe el rango inicial
    - Como segundo parametro el rango final 
    - El tercer parámetro es opcional y determina el paso de la secuencia. Por ejemplo, si especificas un paso de 2, la secuencia será de dos en dos; si es de 3, será de tres en tres, y así sucesivamente.
El rango final no se toma en cuenta

In [2]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

- `np.zeros` : Se utiliza para crear matrices llenas de ceros. Es util para incializar matrices y crear esquemas previamente definidos para ser utilizados posteriormente.

In [3]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])