In [ ]:
import numpy as np

# Shape - reshape

En Numpy, shape y reshape son atributos y métodos que se utilizan para manipular la forma (dimensiones y tamaño) de los arrays.

## Shape

shape:
- Atributo: En Numpy, shape es un atributo de los arrays que devuelve una tupla que describe la forma del array, es decir, el número de elementos en cada dimensión.
- Uso: Puedes acceder al atributo shape de un array para obtener información sobre sus dimensiones. 



In [6]:

arr = np.random.randint(1,10,(3,2))
arr

array([[7, 4],
       [6, 4],
       [1, 8]])

Si tomamos el array que acabamos de crear y aplicamos la propiedad shape, nos va a arrojar exactamente la estructura con la que lo definimos.
Shape nos indica cuantas filas y cuantas columnas, si aplicamos esta propiedad a un tensor nos indicara las dimensiones filas y columnas que conforman a este.

In [7]:
arr.shape

(3, 2)

## reshape

- Método: En Numpy, reshape es un método que se utiliza para cambiar la forma de un array, es decir, reorganizar sus elementos en una nueva forma sin cambiar su contenido.
- Uso: Puedes utilizar el método reshape() para cambiar la forma de un array, especificando las nuevas dimensiones deseadas.

**Recibe los siguientes parametros**

- nueva forma (newshape): Este parámetro es obligatorio y especifica la nueva forma que se desea para el array. Puede ser un entero o una tupla de enteros que representan las dimensiones del nuevo array. Por ejemplo:
    - Un solo entero: Si se proporciona un solo entero, el array se remodelará en un array unidimensional de ese tamaño.
    - Tupla de enteros: Si se proporciona una tupla de enteros, cada entero representa el tamaño de cada dimensión del nuevo array.
- orden (order): (Opcional) Este parámetro especifica el orden en el que se deben leer los elementos del array original para reorganizarlos en el nuevo array. 

Reshape es un comando que nos cambia la forma en la que esta establecido un array. Esto es muy utyil por que muchas veces nuestro software es entrenado con una forma especifica y en ocasiones sera necesario aplicar este metodo para despues ser analizado.

In [8]:
arr.reshape(1,6)

array([[7, 4, 6, 4, 1, 8]])

In [9]:
arr.reshape(2,3)

array([[7, 4, 6],
       [4, 1, 8]])

### Ordenacion al hacer reshape

Podemos ejecutar  shape como metodo desde numpy sin necesidad de aplicarlo con notacion de puntos sobre el array. 
De esta forma podemos pasar mas parametros como la ordenacion.
Como primer parametro indicamos el array que se reformara, como segundo, la nueva forma y comom tecero el orden .
Puede ser 'C' (por defecto) para ordenar por filas (row-major) o 'F' para ordenar por columnas (column-major). Este parámetro es útil principalmente cuando se trata de arrays multidimensionales.

In [10]:
# Array original.
arr

array([[7, 4],
       [6, 4],
       [1, 8]])

In [12]:
np.reshape(arr, (2,3), 'C')

array([[7, 4, 6],
       [4, 1, 8]])