In [3]:
import numpy as np

arr = np.random.randint(1,20,10)
arr

array([17, 19, 10,  5, 13, 19, 13,  1, 16, 12])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[17, 19, 10,  5, 13],
       [19, 13,  1, 16, 12]])

# Funciones principales

## max
```max``` : Nos devuelve el numero mas grande dentro del array.

In [5]:
print(arr.max())
print(matriz.max())


19
19


> 💡 El eje 0 correpsonde a las columnas y el eje 1 a las filas 

La funcion max recibe como parametro un 0 o un 1, con lo cual indicamos que nos devuelva los valores mas altos ya sea por fila o por columnas

In [9]:
matriz

array([[10, 13, 13,  6, 17],
       [16,  6, 19,  3, 17]])

In [8]:
# Valor mas alto por filas

matriz.max(1)

array([17, 19])

In [6]:
# Valor mas alto por columnas
matriz.max(0)

array([19, 19, 10, 16, 13])

De esta manera podemos navegar por las diferentes dimensiones y matrices para obtener los beneficios de la funcion max.

## argmax

Este es nos devuelve el indice en donde se encuentra el valor mas grande de nuestro array. 

In [12]:
matriz

array([[10, 13, 13,  6, 17],
       [16,  6, 19,  3, 17]])

In [14]:
arr.argmax()

7

In [13]:
matriz.argmax()

7

En este caso solo nos muestra el de menor indice, no nos arroja las dos posiciones de la matriz

## min

Se comporta igual que max pero en este caso devolviendonos el valor minimo del array o matriz.

In [17]:
print(arr.min())
print(matriz.min())
print(matriz.min(0))
print(matriz.min(1))


3
3
[10  6 13  3 17]
[6 3]


## ptp (peak to peak)

Se utiliza para calcular la diferencia entre el valor máximo y el valor mínimo de un array a lo largo de un eje especificado.

In [19]:
arr

array([10, 13, 13,  6, 17, 16,  6, 19,  3, 17])

In [20]:
arr.ptp()

16

En este caso nos devuelve la diferencia entre 19 y 3

In [7]:
print(matriz)
print(matriz.ptp())
print(matriz.ptp(0))
print(matriz.ptp(1))

[[17 19 10  5 13]
 [19 13  1 16 12]]
18
[ 2  6  9 11  1]
[14 18]


**Sintaxis alternativa**

```numpy.ptp(a, axis=None)```
- ```a```: El array de NumPy del cual se calculará la diferencia entre el valor máximo y el valor mínimo.
- ```axis``` (opcional): El eje a lo largo del cual se calculará la diferencia. Si se omite o se establece en None, se calculará la diferencia a lo largo de todo el array. Si se proporciona un valor, se calculará la diferencia a lo largo del eje especificado.


## percentile


Un percentil es una medida estadística que indica el valor por debajo del cual cae un porcentaje específico de observaciones en un conjunto de datos ordenado. Es una forma de dividir un conjunto de datos en partes iguales basadas en su distribución.

Por ejemplo, el percentil 50 (también conocido como mediana) es el valor que separa al conjunto de datos en dos partes iguales: el 50% de los datos están por encima de este valor y el 50% están por debajo. De manera similar, el percentil 25 (primer cuartil) es el valor por debajo del cual cae el 25% de los datos, y el percentil 75 (tercer cuartil) es el valor por debajo del cual cae el 75% de los datos.

In [13]:
print(matriz)
print(arr)
np.percentile(matriz, 50)
np.percentile(arr, 50)

[[17 19 10  5 13]
 [19 13  1 16 12]]
[17 19 10  5 13 19 13  1 16 12]


13.0

In [14]:
np.percentile(arr, 0)

1.0

Si ejecutamos percentil 0 nos arroja el numero ams bajo.
Si ejecutamos percentile 100 nos arroja el numero mas alto.

## Sort

La función `numpy.sort()` se utiliza para ordenar los elementos de un array.

In [15]:
sorted_array = np.sort(arr)
print("Array ordenado:", sorted_array)

Array ordenado: [ 1  5 10 12 13 13 16 17 19 19]


## mean

La función `numpy.mean()` se utiliza para calcular la media (promedio) de los elementos de un array.


In [16]:
media = np.mean(arr)
media_matriz = np.mean(matriz)
print("Media array:", media)
print("Media matriz:", media_matriz)

Media array: 12.5
Media matriz: 12.5


## std

La función `numpy.std()` se utiliza para calcular la desviación estándar de los elementos de un array.

En NumPy, la desviación estándar es una medida de la dispersión de los valores en un conjunto de datos. Se calcula como la raíz cuadrada de la varianza, que a su vez es la media de los cuadrados de las desviaciones de cada valor de la media.

En otras palabras, la desviación estándar nos dice qué tan lejos, en promedio, se encuentran los valores del conjunto de datos de su valor medio. Un valor de desviación estándar bajo indica que los valores están agrupados cerca de la media, mientras que un valor alto indica que los valores están más dispersos.

In [17]:
desviacion_estandar = np.std(arr)
print("Desviación estándar:", desviacion_estandar)

Desviación estándar: 5.5901699437494745


La desviación estándar es una herramienta importante para analizar datos en NumPy. Se puede utilizar para comparar la dispersión de diferentes conjuntos de datos, para identificar valores atípicos y para construir modelos estadísticos.

## var

La función `var()` de NumPy se utiliza para calcular la varianza de un array de datos. La varianza es una medida de la dispersión de los valores en un conjunto de datos. Se calcula como la media de los cuadrados de las desviaciones de cada valor de la media.

La varianza nos dice qué tan lejos, en promedio, se encuentran los valores del conjunto de datos de su valor medio. Un valor de varianza bajo indica que los valores están agrupados cerca de la media, mientras que un valor alto indica que los valores están más dispersos.

La función `var()` tiene dos argumentos opcionales:

- `axis`: El eje a lo largo del cual se calculará la varianza. Si no se especifica, la varianza se calculará sobre el array aplanado.
- `ddof`: El número de grados de libertad. Este argumento se utiliza para ajustar el cálculo de la varianza para que no esté sesgado. El valor predeterminado es 0.

In [18]:
varianza = np.var(arr)
print("Varianza:", varianza)

Varianza: 31.25


La función `var()` toma un array como argumento y devuelve la varianza de los valores en el array. La varianza se calcula por defecto sobre el array aplanado, pero también se puede especificar un eje a lo largo del cual se calculará la varianza.

## Diferencia en varianza y desviacion estandar

La varianza y la desviación estándar son dos medidas de dispersión estrechamente relacionadas, pero son distintas. La varianza se mide en unidades cuadradas, mientras que la desviación estándar se mide en las mismas unidades que los datos originales. Esto significa que la desviación estándar es más fácil de interpretar que la varianza.

La desviación estándar se calcula como la raíz cuadrada de la varianza. En otras palabras, la desviación estándar nos dice qué tan lejos, en unidades originales, se encuentran los valores del conjunto de datos de su valor medio.

## concatenate()

La función `concatenate()` de NumPy se utiliza para unir dos o más arrays a lo largo de un eje especificado. Es una herramienta fundamental para trabajar con arrays de diferentes formas y tamaños.

**Parámetros:**

- `array1, array2`, ..., arrayN: Los arrays que se quieren unir. Deben tener la misma forma, excepto en la dimensión correspondiente al eje especificado.
- `axis`: (Opcional) El eje a lo largo del cual se unirán los arrays. El valor predeterminado es 0, que significa que los arrays se unirán en la primera dimensión.
- `out`: (Opcional) Un array de salida preexistente en el que se almacenará el resultado. Si no se especifica, se creará un nuevo array.

In [25]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,9])

print(a, b)

[1 2 3 4 5] [8 7 9]


In [28]:
array_concatenado = np.concatenate((a,b))
print(array_concatenado)

[1 2 3 4 5 8 7 9]


## expand_dims()

La función `expand_dims()` de NumPy se utiliza para insertar una nueva dimensión en un array en un lugar específico. Esto puede ser útil para trabajar con arrays de diferentes formas y tamaños.

- **Sintaxis**

`np.expand_dims(array, axis)`

- **Parámetros:**

- `array`: El array al que se le quiere insertar una nueva dimensión.
- `axis`: El eje en el que se insertará la nueva dimensión.


In [29]:
array = np.array([1, 2, 3])
expandido = np.expand_dims(array, axis=0)
print("Array expandido:", expandido)
print("Forma del array expandido:", expandido.shape)

Array expandido: [[1 2 3]]
Forma del array expandido: (1, 3)


### Uso de expand_dims para concatenar

Supongamos que queremos concatenar dos arrays unidimensionales como si fueran filas de una matriz bidimensional.

In [30]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Expandir dimensiones para que ambos arrays sean 2D
array1_expandido = np.expand_dims(array1, axis=0)
array2_expandido = np.expand_dims(array2, axis=0)

# Concatenar a lo largo del eje 0 (filas)
concatenado = np.concatenate((array1_expandido, array2_expandido), axis=0)
print("Array concatenado:\n", concatenado)

Array concatenado:
 [[1 2 3]
 [4 5 6]]


***Ejemplo sin expand_dims***

In [32]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

arr_concatenados = np.concatenate((array1, array2))
print("Array concatenado: \n", arr_concatenados)

Array concatenado: 
 [1 2 3 4 5 6]
