In [3]:
import numpy as np

arr = np.random.randint(1,20,10)
arr

array([10, 13, 13,  6, 17, 16,  6, 19,  3, 17])

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[10, 13, 13,  6, 17],
       [16,  6, 19,  3, 17]])

# Funciones principales

## max
```max``` : Nos devuelve el numero mas grande dentro del array.

In [6]:
print(arr.max())
print(matriz.max())


19
19


> 💡 El eje 0 correpsonde a las columnas y el eje 1 a las filas 

La funcion max recibe como parametro un 0 o un 1, con lo cual indicamos que nos devuelva los valores mas altos ya sea por fila o por columnas

In [9]:
matriz

array([[10, 13, 13,  6, 17],
       [16,  6, 19,  3, 17]])

In [8]:
# Valor mas alto por filas

matriz.max(1)

array([17, 19])

In [11]:
# Valor mas alto por columnas
matriz.max(0)

array([16, 13, 19,  6, 17])

De esta manera podemos navegar por las diferentes dimensiones y matrices para obtener los beneficios de la funcion max.

## argmax

Este es nos devuelve el indice en donde se encuentra el valor mas grande de nuestro array. 

In [12]:
matriz

array([[10, 13, 13,  6, 17],
       [16,  6, 19,  3, 17]])

In [14]:
arr.argmax()

7

In [13]:
matriz.argmax()

7

En este caso solo nos muestra el de menor indice, no nos arroja las dos posiciones de la matriz

## min

Se comporta igual que max pero en este caso devolviendonos el valor minimo del array o matriz.

In [17]:
print(arr.min())
print(matriz.min())
print(matriz.min(0))
print(matriz.min(1))


3
3
[10  6 13  3 17]
[6 3]


## ptp (peak to peak)

Se utiliza para calcular la diferencia entre el valor máximo y el valor mínimo de un array a lo largo de un eje especificado.

In [19]:
arr

array([10, 13, 13,  6, 17, 16,  6, 19,  3, 17])

In [20]:
arr.ptp()

16

En este caso nos devuelve la diferencia entre 19 y 3

In [24]:
print(matriz)
print(matriz.ptp())
print(matriz.ptp(0))
print(matriz.ptp(1))

[[10 13 13  6 17]
 [16  6 19  3 17]]
16
[6 7 6 3 0]
[11 16]


**Sintaxis alternativa**

```numpy.ptp(a, axis=None)```
- ```a```: El array de NumPy del cual se calculará la diferencia entre el valor máximo y el valor mínimo.
- ```axis``` (opcional): El eje a lo largo del cual se calculará la diferencia. Si se omite o se establece en None, se calculará la diferencia a lo largo de todo el array. Si se proporciona un valor, se calculará la diferencia a lo largo del eje especificado.


## percentile


Un percentil es una medida estadística que indica el valor por debajo del cual cae un porcentaje específico de observaciones en un conjunto de datos ordenado. Es una forma de dividir un conjunto de datos en partes iguales basadas en su distribución.

Por ejemplo, el percentil 50 (también conocido como mediana) es el valor que separa al conjunto de datos en dos partes iguales: el 50% de los datos están por encima de este valor y el 50% están por debajo. De manera similar, el percentil 25 (primer cuartil) es el valor por debajo del cual cae el 25% de los datos, y el percentil 75 (tercer cuartil) es el valor por debajo del cual cae el 75% de los datos.