# Operaciones con numpy

Numpy es una biblioteca fundamental para la computación científica en Python, que proporciona un soporte robusto para arrays y matrices multidimensionales, así como una amplia colección de funciones matemáticas para operar con estos arrays de manera eficiente.

In [10]:
import numpy as np

lista = [1,2]
print(lista)

[1, 2]


In [2]:
lista * 2

[1, 2, 1, 2]

Si queremos ejecutar una multiplicacion en donde queremos que los valores de nuetsra lista sean multiplicados por dos, pythhon por si solo no entendera, y en su lugar nos devolvera la lista duplicada con los mismos valores.

In [7]:
arr = np.arange(0,10)
print(arr)
arr2 = arr.copy()
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Operaciones Elemento a Elemento
Numpy realiza operaciones aritméticas de forma elemento a elemento. Esto significa que cuando sumas, restas, multiplicas o divides dos arrays, cada operación se aplica a los elementos correspondientes de los arrays:

In [5]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

En este caso al dividir 1 entre 0 nos arroja un error pero aun asi, numpy continua con la operacion de los demas elementos.

In [7]:
1 / arr

/tmp/ipykernel_11658/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr / arr2

/tmp/ipykernel_11658/1444868932.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## Operaciones en matrices

En Numpy, las operaciones matemáticas en matrices se manejan de manera similar a cómo se manejan en arrays unidimensionales, pero con algunas diferencias y funciones adicionales específicas para trabajar con estructuras bidimensionales y multidimensionales. 

In [14]:
a = arr.reshape(2,5)
b = np.array([[1,2,3,7,9],[4,5,6,8,0]])


In [15]:
a 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
b

array([[1, 2, 3, 7, 9],
       [4, 5, 6, 8, 0]])

Las operaciones aritméticas entre matrices se realizan elemento a elemento. Esto significa que, al igual que con arrays unidimensionales, cada operación se aplica a los elementos correspondientes de las matrices:

In [17]:
a + b

array([[ 1,  3,  5, 10, 13],
       [ 9, 11, 13, 16,  9]])

In [18]:
a * b

array([[ 0,  2,  6, 21, 36],
       [20, 30, 42, 64,  0]])

In [19]:
a / b

/tmp/ipykernel_9814/1286629031.py:1: RuntimeWarning: divide by zero encountered in divide
  a / b


array([[0.        , 0.5       , 0.66666667, 0.42857143, 0.44444444],
       [1.25      , 1.2       , 1.16666667, 1.        ,        inf]])

In [20]:
a - b

array([[-1, -1, -1, -4, -5],
       [ 1,  1,  1,  0,  9]])

## Funcion matmul

La función numpy.matmul en Numpy se utiliza para realizar la multiplicación de matrices. Esta función se puede usar para multiplicar dos matrices (dos-dimensionales) o más generalmente, dos arrays de cualquier dimensión siempre que las formas sean compatibles para la multiplicación matricial.

- Sintaxis:

`numpy.matmul(a, b, out=None)`

**Parámetros**:
- a, b: Los arrays de entrada para la multiplicación.
- out: Array de salida opcional. Debe tener la forma correcta para almacenar el resultado.


**Características Principales:**

- Multiplicación de matrices 2D: Cuando ambos a y b son matrices 2D, numpy.matmul realiza la multiplicación matricial estándar.
- Multiplicación de vectores: Si uno de los argumentos es un vector (1D) y el otro es una matriz (2D), numpy.matmul realiza una multiplicación vector-matriz adecuada.
- Broadcasting: numpy.matmul es compatible con el broadcasting, lo que permite la multiplicación de arrays con formas compatibles de manera eficiente.

### Matriz transpuesta

La transpuesta de una matriz es una operación en la que una matriz invierte sus valores sobre su diagonal, lo que quiere decir que la transpuesta de una matriz de tamaño m por n resultará en una matriz de tamaño n por m.

> **La transposición no modifica los valores individuales de los elementos, sino que simplemente cambia su posición dentro de la matriz.**

En este caso para realizar operaciones con la funcion matmul es necesario que los valores de las matrices ubicados en las filas hagan match con los valores ubicados en las columnas, para ello es necesario hacer una transpuesta de los valores en ambos arrays.

In [25]:
print(a)
a.T

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [24]:
np.matmul(a, b.T)

array([[ 65,  41],
       [175, 156]])